[package]
name = "erl_dist"
version = "0.1.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Rust Implementation of Erlang Distribution Protocol"
homepage = "https://github.com/sile/erl_dist"
repository = "https://github.com/sile/erl_dist"
readme = "README.md"
keywords = ["erlang"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/erl_dist"}

[dependencies]
eetf = "0.3"
futures = "0.1"
handy_async = "0.2"
md5 = "0.3"
rand = "0.3"
bitflags = "0.8"

[dev-dependencies]
clap = "2"
fibers = "0.1"